name: Release and Publish

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v0.1.0, v1.2.3, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Allow the job to get a token from OIDC
      contents: write # Allow the job to create a GitHub Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Hatch
        run: pip install hatch

      - name: Build package
        run: hatch build

      - name: Publish to PyPI
        run: hatch publish

      - name: Create GitHub Release
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            # Use the tag for the release name and notes
            gh release create ${{ github.ref_name }} \
                --title ${{ github.ref_name }} \
                --notes "Release ${{ github.ref_name }}" \
                dist/* # Attach the built wheel and sdist
